/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pckgInterface;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

import CoreClasses.SeperateFileContent;
import java.awt.Color;
import java.util.Random;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Shane
 */
public class frmDuplicatedCode extends javax.swing.JFrame {

    /**
     * Creates new form frmDuplicatedCode
     */
    SeperateFileContent SFC = new SeperateFileContent();
    frmCodeSmellMenu CSM = new frmCodeSmellMenu();
    public Vector<Object> SFCBlocks=new Vector<Object>();
    public static Highlighter.HighlightPainter painter;
    
    public Vector<String> DupLines=new Vector<String>();
    public Vector<Color> ColorCodes=new Vector<Color>();
    public frmDuplicatedCode() {
        initComponents();
    }
    public frmDuplicatedCode(SeperateFileContent SFCTemp, frmCodeSmellMenu CSMemp, Vector SFCBlocksTemp) {
        
        SFC = SFCTemp;
        CSM = CSMemp;
        SFCBlocks = SFCBlocksTemp;
        initComponents();
        for(int i=0;i<SFCBlocksTemp.size();i++)
        {
            //ClassDefinition cdTemp = (ClassDefinition)SFC.getClassDetails(i);
            cmbFileList.addItem(((SeperateFileContent)SFCBlocksTemp.elementAt(i)).fileName);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnFindDuplicateCodes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCodeDisplay = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        cmbFileList = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDuplicatedLines = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("D u p l i c a t e d    C o d e    D e t e c t o r");

        btnFindDuplicateCodes.setText("Find Duplicated Codes");
        btnFindDuplicateCodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindDuplicateCodesActionPerformed(evt);
            }
        });

        txtAreaCodeDisplay.setColumns(20);
        txtAreaCodeDisplay.setRows(5);
        jScrollPane1.setViewportView(txtAreaCodeDisplay);

        jLabel9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel9.setText("Select File");

        cmbFileList.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N

        txtDuplicatedLines.setColumns(20);
        txtDuplicatedLines.setRows(5);
        jScrollPane2.setViewportView(txtDuplicatedLines);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)
                        .addComponent(cmbFileList, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFindDuplicateCodes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9))
                    .addComponent(cmbFileList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindDuplicateCodes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindDuplicateCodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindDuplicateCodesActionPerformed
        // TODO add your handling code here:
        
        String fileName = cmbFileList.getSelectedItem().toString();
        String fileData="";
        
        DupLines.removeAllElements();
        ColorCodes.removeAllElements();
        
        for(int sf=0;sf<SFCBlocks.size();sf++)
        {
            if((((SeperateFileContent)SFCBlocks.elementAt(sf)).fileName).equals(fileName))
            {
                    //cmdViewCodes.setEnabled(true);
                
                SeperateFileContent SFCTemp = (SeperateFileContent)SFCBlocks.elementAt(sf);

                SFC = SFCTemp;
                
                //String fileData="";

                for(int i=0;i<SFC.FileContentLineByLineWithoutComments.size();i++)
                {
                    fileData = fileData + (i+1)+ "  " +  SFC.getVectorLineDetailsWithoutComments(i) + "\n";
                }

                txtAreaCodeDisplay.setText(fileData.toString());     

                int x=0;
                
                for(int l=0;l<SFC.FileContentLineByLineWithoutComments.size();l++)
                {
                    String curLine = SFC.FileContentLineByLineWithoutComments.elementAt(l);

                    Random randomGenerator = new Random();
                    int red = randomGenerator.nextInt(255);
                    int green = randomGenerator.nextInt(255);
                    int blue = randomGenerator.nextInt(255);

                    
                    Color randomColour = new Color(red,green,blue);
                    
                    painter = new DefaultHighlighter.DefaultHighlightPainter((Color)randomColour);
                    x=0;
                    if(!((curLine.contains("{"))|(curLine.contains("}"))|(curLine.contains("else"))|(curLine.contains("catch"))|(curLine.contains("try"))))      
                    {
                        
                        for(int lc=l+1;lc<SFC.FileContentLineByLineWithoutComments.size();lc++)
                        {
                            if(curLine.equals(SFC.FileContentLineByLineWithoutComments.elementAt(lc)))
                            {
                                if(x==0)
                                {
                                    ColorCodes.add(randomColour);
                                    DupLines.add(curLine);
                                }
                                highlight(txtAreaCodeDisplay, curLine);
                                System.out.println(SFC.FileContentLineByLineWithoutComments.elementAt(lc));
                                x++;
                            }                
                        }
                    }
                }
                
                String dupLineContent = "";
                for(int d=0;d<DupLines.size();d++)
                {
                    dupLineContent = dupLineContent + DupLines.elementAt(d)+"\n";
                }
                txtDuplicatedLines.setText("");
                txtDuplicatedLines.setText(dupLineContent);
                
                for(int d1=0;d1<DupLines.size();d1++)
                {
                    painter = new DefaultHighlighter.DefaultHighlightPainter((Color)ColorCodes.elementAt(d1));
                    highlight(txtDuplicatedLines, DupLines.elementAt(d1));
                    //dupLineContent = dupLineContent + DupLines.elementAt(d);
                }
            }
        }
    }//GEN-LAST:event_btnFindDuplicateCodesActionPerformed

    
    public static void highlight(JTextComponent textComp, String pattern) {

    try {
        
        
        Highlighter hilite = textComp.getHighlighter();
        javax.swing.text.Document doc = textComp.getDocument();
        String text = doc.getText(0, doc.getLength());
        int pos = 0;

        // Search for pattern
        while ((pos = text.indexOf(pattern, pos)) >= 0) {
            // Create highlighter using private painter and apply around pattern
            hilite.addHighlight(pos, pos + pattern.length(), painter);
            pos += pattern.length();
        }
    } catch (BadLocationException e) {
    }
}
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
         CSM.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDuplicatedCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDuplicatedCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDuplicatedCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDuplicatedCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDuplicatedCode().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFindDuplicateCodes;
    private javax.swing.JComboBox cmbFileList;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAreaCodeDisplay;
    private javax.swing.JTextArea txtDuplicatedLines;
    // End of variables declaration//GEN-END:variables
}
