/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pckgInterface;

import CoreClasses.ClassDefinition;
import CoreClasses.MethodDefinition;
import CoreClasses.SeperateFileContent;
import Smells.featureEnvy;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shane
 */
public class frmFeatureEnvy extends javax.swing.JFrame {

    /**
     * Creates new form frmFeatureEnvy
     */
    SeperateFileContent SFC = new SeperateFileContent();
    frmCodeSmellMenu CSM = new frmCodeSmellMenu();
    public Vector<Object> SFCBlocks=new Vector<Object>();
    public frmFeatureEnvy() {
        initComponents();
    }
     public frmFeatureEnvy(SeperateFileContent SFCTemp, frmCodeSmellMenu CSMemp, Vector SFCBlocksTemp) {
        
        SFC = SFCTemp;
        CSM = CSMemp;
        SFCBlocks = SFCBlocksTemp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowFeatureEnvyResults = new javax.swing.JTable();
        btnProcessData = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCodeVeiw = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel6.setText("*Click on a Feature Envy Detail to View the Code");

        jLabel5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel5.setText("Feature Envy Details");

        jLabel4.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("F e a t u r e    E n v y    D e t e c t o r");

        tblShowFeatureEnvyResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblShowFeatureEnvyResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblShowFeatureEnvyResultsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblShowFeatureEnvyResults);

        btnProcessData.setText("Apply Smell");
        btnProcessData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessDataActionPerformed(evt);
            }
        });

        txtCodeVeiw.setColumns(20);
        txtCodeVeiw.setRows(5);
        txtCodeVeiw.setText("\n\n*Click on Feature Envy Record to \n View Code");
        jScrollPane2.setViewportView(txtCodeVeiw);

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setText("Code View");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnProcessData, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(55, 55, 55)
                .addComponent(btnProcessData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblShowFeatureEnvyResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblShowFeatureEnvyResultsMouseClicked
        // TODO add your handling code here:

        String selectedRowMethName=String.valueOf(tblShowFeatureEnvyResults.getModel().getValueAt(tblShowFeatureEnvyResults.getSelectedRow(), 0));
        String selectedRowFileName=String.valueOf(tblShowFeatureEnvyResults.getModel().getValueAt(tblShowFeatureEnvyResults.getSelectedRow(), 1));
        int selectedRowStartLine=Integer.parseInt(String.valueOf(tblShowFeatureEnvyResults.getModel().getValueAt(tblShowFeatureEnvyResults.getSelectedRow(), 3)));
        int StartLineNo=0;
        String MethName="";

        String fileName = selectedRowFileName;
        // String fileData="";
        for(int sf=0;sf<SFCBlocks.size();sf++)
        {
            if((((SeperateFileContent)SFCBlocks.elementAt(sf)).fileName).equals(fileName))
            {

                    SeperateFileContent SFCTemp = (SeperateFileContent)SFCBlocks.elementAt(sf);

                    SFC = SFCTemp;


                    for(int m=0;m<SFC.MethodCodeBlocks.size();m++)
                    {
                        StartLineNo = ((MethodDefinition)SFC.MethodCodeBlocks.elementAt(m)).startLineNo;
                        MethName = ((MethodDefinition)SFC.MethodCodeBlocks.elementAt(m)).method_name;

                        if((MethName.equals(selectedRowMethName))&((StartLineNo==selectedRowStartLine)))
                        {
                            txtCodeVeiw.setText(((MethodDefinition)SFC.MethodCodeBlocks.elementAt(m)).content.toString());
                        }
                    }

            }
        }
    }//GEN-LAST:event_tblShowFeatureEnvyResultsMouseClicked

    private void btnProcessDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessDataActionPerformed
        //lblSmellInfo.setText("Shown below is a list of Long Methods taking 80 Lines as the average length of a method.");
        featureEnvy FE = new featureEnvy();

        //DisplayTableData(LC.getLargeClasses(SFC,SFCBlocks));
        DisplayTableData(FE.getFeaturEnvy(SFCBlocks));
        //lblMaxPrim.setText(String.valueOf(PO.MAX_PRIMITIVE_VARIABLE));
        //lblMaxParam.setText(String.valueOf(PO.MAX_PARAMETER_VARIABLE));
    }//GEN-LAST:event_btnProcessDataActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        CSM.setVisible(true);
    }//GEN-LAST:event_formWindowClosed
    public void DisplayTableData(DefaultTableModel model)
    {
        tblShowFeatureEnvyResults.setModel(model);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFeatureEnvy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFeatureEnvy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFeatureEnvy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFeatureEnvy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFeatureEnvy().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessData;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblShowFeatureEnvyResults;
    private javax.swing.JTextArea txtCodeVeiw;
    // End of variables declaration//GEN-END:variables
}
